-- TELECOM CUSTOMER CHURN ANALYSIS

CREATE DATABASE telecom_churn_analysis;
USE telecom_churn_analysis;


-- 1. DATA PREVIEW
-- Q1. What does the cleaned telecom customer dataset look like?

SELECT * FROM telecom_data LIMIT 10;


-- 2. OVERALL CUSTOMER ANALYSIS
-- Q2. How many total customers are present in the dataset?

SELECT COUNT(*) AS Total_Customers
    FROM telecom_data;


-- Q3. How many customers have churned?

SELECT COUNT(*) AS Churned_Customers
    FROM telecom_data
    WHERE `Customer Status` = 'Churned';


-- Q4. What is the overall churn rate?

SELECT ROUND(
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
    * 100.0 / COUNT(*), 2
) AS Churn_Rate
    FROM telecom_data;


-- 3. CONTRACT ANALYSIS
-- Q5. Which contract type has the highest churn rate?

SELECT `Contract`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    GROUP BY `Contract`
    ORDER BY Churn_Rate DESC;


-- Q6. How many churned customers are there for each contract type?

SELECT `Contract`,
    COUNT(*) AS Churned_Customers
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    GROUP BY `Contract`
    ORDER BY Churned_Customers DESC;


-- 4. INTERNET SERVICE ANALYSIS
-- Q7. How does churn rate differ between customers
--     with and without internet service?

SELECT `Internet Service`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    GROUP BY `Internet Service`
    ORDER BY Churn_Rate DESC;


-- Q8. Which internet type has the highest churn rate?

SELECT `Internet Type`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    WHERE `Internet Type` IS NOT NULL
    GROUP BY `Internet Type`
    ORDER BY Churn_Rate DESC;


-- 5. TENURE ANALYSIS
-- Q9. Which tenure group has the highest churn rate?

SELECT `Tenure Group`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    GROUP BY `Tenure Group`
    ORDER BY Churn_Rate DESC;


-- Q10. What is the average tenure of churned and retained customers?

SELECT `Customer Status`,
    ROUND(AVG(`Tenure in Months`), 2) AS Average_Tenure
    FROM telecom_data
    GROUP BY `Customer Status`;


-- 6. PAYMENT METHOD ANALYSIS
-- Q11. Which payment method has the highest churn rate?

SELECT `Payment Method`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    GROUP BY `Payment Method`
    ORDER BY Churn_Rate DESC;


-- 7. DEMOGRAPHIC ANALYSIS
-- Q12. Which age group has the highest churn rate?

SELECT `Age Group`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    GROUP BY `Age Group`
    ORDER BY Churn_Rate DESC;


-- Q13. Does churn rate differ by gender?

SELECT `Gender`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    GROUP BY `Gender`
    ORDER BY Churn_Rate DESC;


-- 8. REVENUE ANALYSIS
-- Q14. What is the total revenue generated by all customers?

SELECT ROUND(SUM(`Total Revenue`), 2) AS Total_Revenue
    FROM telecom_data;


-- Q15. How much revenue was generated by churned customers?

SELECT ROUND(SUM(`Total Revenue`), 2) AS Churned_Revenue
    FROM telecom_data
    WHERE `Customer Status` = 'Churned';


-- Q16. What percentage of total revenue comes from churned customers?

SELECT ROUND(
    SUM(CASE
        WHEN `Customer Status` = 'Churned'
        THEN `Total Revenue`
        ELSE 0
    END) * 100.0 / SUM(`Total Revenue`), 2
) AS Churned_Revenue_Share
    FROM telecom_data;


-- Q17. What is the average monthly charge for churned
--     and retained customers?

SELECT `Customer Status`,
    ROUND(AVG(`Monthly Charge`), 2) AS Average_Monthly_Charge
    FROM telecom_data
    GROUP BY `Customer Status`;


-- 9. CUSTOMER VALUE ANALYSIS
-- Q18. Who are the top 10 customers based on total revenue?

SELECT `Customer ID`,
    ROUND(`Total Revenue`, 2) AS Total_Revenue
    FROM telecom_data
    ORDER BY `Total Revenue` DESC
    LIMIT 10;


-- Q19. Which high-value customers have churned?

SELECT `Customer ID`,
    ROUND(`Total Revenue`, 2) AS Total_Revenue,
    `Contract`,
    `Tenure in Months`,
    `Customer Status`
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    ORDER BY `Total Revenue` DESC
    LIMIT 10;


-- 10. CHURN CATEGORY ANALYSIS
-- Q20. Which churn category contributes the most churned customers?

SELECT `Churn Category`,
    COUNT(*) AS Churned_Customers
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    AND `Churn Category` IS NOT NULL
    GROUP BY `Churn Category`
    ORDER BY Churned_Customers DESC;


-- 11. CHURN REASON ANALYSIS
-- Q21. What are the top 10 reasons customers churn?

SELECT `Churn Reason`,
    COUNT(*) AS Churned_Customers
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    AND `Churn Reason` IS NOT NULL
    GROUP BY `Churn Reason`
    ORDER BY Churned_Customers DESC
    LIMIT 10;


-- Q22. Which churn reasons are associated with the highest revenue loss?

SELECT `Churn Reason`,
    COUNT(*) AS Churned_Customers,
    ROUND(SUM(`Total Revenue`), 2) AS Revenue_Lost
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    AND `Churn Reason` IS NOT NULL
    GROUP BY `Churn Reason`
    ORDER BY Revenue_Lost DESC
    LIMIT 10;


-- 12. OFFER ANALYSIS
-- Q23. Which offer has the highest churn rate?

SELECT `Offer`,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        AS Churned_Customers,
    ROUND(
        SUM(CASE WHEN `Customer Status` = 'Churned' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    ) AS Churn_Rate
    FROM telecom_data
    GROUP BY `Offer`
    ORDER BY Churn_Rate DESC;


-- 13. BUSINESS ANALYSIS
-- Q24. Which internet type generates the highest churned revenue?

SELECT `Internet Type`,
    COUNT(*) AS Churned_Customers,
    ROUND(SUM(`Total Revenue`), 2) AS Churned_Revenue
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    AND `Internet Type` IS NOT NULL
    GROUP BY `Internet Type`
    ORDER BY Churned_Revenue DESC;


-- Q25. Which contract type generates the highest churned revenue?

SELECT `Contract`,
    COUNT(*) AS Churned_Customers,
    ROUND(SUM(`Total Revenue`), 2) AS Churned_Revenue
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    GROUP BY `Contract`
    ORDER BY Churned_Revenue DESC;


-- 14. ADVANCED SQL
-- Q26. How can customers be ranked based on total revenue?

SELECT `Customer ID`,
    ROUND(`Total Revenue`, 2) AS Customer_Revenue,
    RANK() OVER (
        ORDER BY `Total Revenue` DESC
    ) AS Revenue_Rank
    FROM telecom_data
    LIMIT 10;


-- Q27. How can churned customers be ranked based on total revenue?

SELECT `Customer ID`,
    ROUND(`Total Revenue`, 2) AS Customer_Revenue,
    RANK() OVER (
        ORDER BY `Total Revenue` DESC
    ) AS Revenue_Rank
    FROM telecom_data
    WHERE `Customer Status` = 'Churned'
    LIMIT 10;